/**
 * README.md template for generated MCP server
 */
import type { TemplateContext } from '../types.js';

export function generateReadme(ctx: TemplateContext): string {
  return `# ${ctx.projectName}

MCP Server for ${ctx.description}.

## Generated by Bob MCP Forge

This server was generated using the Bob MCP Forge generator tool.

## Requirements

- Node.js >= 20.0.0
- npm or yarn

## Installation

\`\`\`bash
npm install
\`\`\`

## Configuration

Copy \`.env.example\` to \`.env\` and configure:

\`\`\`bash
cp .env.example .env
\`\`\`

### Environment Variables

| Variable | Default | Description |
|----------|---------|-------------|
| \`NODE_ENV\` | \`development\` | Environment mode |
| \`PORT\` | \`3000\` | Server port |
| \`TIMEOUT_MS\` | \`30000\` | Request timeout |
| \`LOG_LEVEL\` | \`info\` | Logging level |

## Usage

### Development

\`\`\`bash
npm run dev
\`\`\`

### Production

\`\`\`bash
npm run build
npm start
\`\`\`

## MCP Inspector

Test your MCP server using the MCP Inspector:

\`\`\`bash
npx @modelcontextprotocol/inspector
\`\`\`

## Tool: ${ctx.toolName}

**Description**: ${ctx.description}

**Input**:
- \`email\` (string, required): Customer email address

**Output**: Customer record as JSON

## Security

- No hardcoded secrets
- Environment variables for all sensitive config
- Input validation on all tool inputs
- Rate limiting enabled (high complexity only)
- Helmet security headers (high complexity only)

## License

MIT
`;
}